# Generated by Django 4.1.7 on 2023-05-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0002_alter_productopedido_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productopedido',
            name='cantidad',
            field=models.PositiveIntegerField(default='', null=True),
        ),
    ]
