# Generated by Django 4.1.7 on 2023-05-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0003_alter_productopedido_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productopedido',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
